import * as colors from "tailwindcss/colors";

const config = {
  content: [
    "./node_modules/grid-uikit/src/**/*.{html,js,svelte,ts}",
    "./src/renderer/**/*.{html,js,svelte,ts}",
  ],
  darkMode: "class",
  theme: {
    fontFamily: {
      body: ["roboto"],
      mono: 'Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
      aldo: "Aldo-SemiBold",
      "roboto-sans": "Roboto Sans",
      "gt-pressura": "GT Pressura Pro M Trial",
      roboto: "Roboto",
      "roboto-mono": "Roboto Mono",
    },
    extend: {
      transitionProperty: {
        width: "width",
      },
      margin: {
        14: "3.5rem",
      },
      zIndex: {
        "-10": "-10",
      },
      cursor: {
        helper: "help",
      },
      minHeight: {
        200: "200px",
        300: "300px",
      },
      height: {
        "16px": "16px",
        "18px": "18px",
        32: "8rem",
        14: "3.5rem",
        64: "16rem",
        72: "18rem",
        128: "32rem",
        600: "600px",
        300: "300px",
        calc: "calc(100vh - 62px)",
      },
      width: {
        "16px": "16px",
        "18px": "18px",
        26: "26px",
      },
      inset: {
        "1/2": "50%",
        1: "1em",
        "9/10": "0.9em",
        "-1": "-1em",
      },
      borderWidth: {
        8: "8px",
        16: "16px",
      },
      colors: {
        black: colors.black,
        white: colors.white,
        gray: colors.neutral,
        green: colors.green,
        red: colors.rose,
        yellow: colors.amber,
        pink: colors.pink,
        purple: colors.purple,
        orange: colors.orange,

        foreground: "var(--foreground)",
        background: "var(--background)",
        shadow: "var(--shadow)",
        "foreground-muted": "var(--foreground-muted)",
        "foreground-soft": "var(--foreground-soft)",
        "foreground-disabled": "var(--foreground-disabled)",

        "background-muted": "var(--background-muted)",
        "background-soft": "var(--background-soft)",

        "popover-background": "var(--popover-background)",
        "popover-selection": "var(--popover-selection)",
        "popover-reference": "var(--popover-reference)",
        "intech-yellow": "#e4ff68",

        primary: {
          DEFAULT: "#1e2628",
          100: "#d3dcde",
          200: "#b6c5c8",
          300: "#99adb2",
          400: "#7c969d",
          500: "#627d83",
          600: "#4d6166",
          700: "#374549",
          800: "#212a2c",
          900: "#0b0e0f",
        },
        warning: {
          DEFAULT: "#EAB308",
          "desaturate-20": "#FFD2B1",
          "desaturate-10": "#FAB17C",
          "saturate-10": "#EF9E4D",
          "saturate-20": "#EF914D",
        },
        error: {
          DEFAULT: "#DC2626",
          "desaturate-10": "#DC4B4B",
          "desaturate-20": "#DC7474",
          "saturate-10": "#DC0F0F",
          "saturate-20": "#FF0000",
        },
        pick: {
          DEFAULT: "#6B7AFF",
          "desaturate-10": "#8591FF",
          "desaturate-20": "#A9AEFF",
          "saturate-10": "#5263FF",
          "saturate-20": "#1F4AC5",
          complementer: "#FFEE52",
        },
        select: {
          DEFAULT: "#47575F",
          "saturate-10": "#3E545F",
          "saturate-20": "#1A2A31",
          "desaturate-10": "#515A5F",
          "desaturate-20": "#788991",
        },
        commit: {
          DEFAULT: "#0BA484",
          "saturate-10": "#00A482",
          "saturate-20": "#006F53",
          "desaturate-10": "#1BA487",
          "desaturate-20": "#5DDCB9",
        },
        unsavedchange: {
          DEFAULT: "#1D4ED8",
        },
        secondary: {
          DEFAULT: "#2a3439",
          "brightness-90": "#eaebeb",
          "brightness-80": "#d4d6d7",
          "brightness-70": "#bfc2c4",
          "brightness-60": "#aaaeb0",
          "brightness-50": "#959a9c",
          "brightness-40": "#7f8588",
          "brightness-30": "#6a7174",
          "brightness-20": "#555d61",
          "brightness-10": "#3f484d",
          "darkness-10": "#262f33",
          "darkness-20": "#222a2e",
          "darkness-30": "#1d2428",
          "darkness-40": "#191f22",
          "darkness-50": "#151a1d",
        },
        highlight: {
          DEFAULT: "#CC5B5B",
          100: "#edc5c5",
          200: "#e19e9e",
          300: "#d57777",
          400: "#c95050",
          500: "#af3636",
          600: "#882a2a",
        },
      },
    },
  },
  plugins: [],
};

module.exports = config;
