export const tooltip_content = {
    "profile_select_local_folder": "This will be the save destination of your profiles on your hard drive.",
    "profile_selection": "Here are your saved profiles listed.",
    "profile_load_to_module": "Don't know.",
    "configuration_ui_events": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_system_events": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_selected_element": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_selected_events": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_actions": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_events": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_copy_all": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_overwrite": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_cut_one": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_copy_one": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_paste_one": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "configuration_remove_one": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "event_init": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "event_button": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "event_encoder": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "event_timer": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "event_potmeter": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_local_variables": "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_encoder_settings" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_code_block" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_condition" : "Egy kedves béka mindig felvidítja az embert a tóparton.",

    "action_led_color" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_led_color_0" : "LED NUM",
    "action_led_color_1" : "Layer",
    "action_led_color_2" : "RED",
    "action_led_color_3" : "GREEM",
    "action_led_color_4" : "BLU",
    "action_led_color_5" : "beautify",

    "action_led_value" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_led_color_0" : "LED NUM",
    "action_led_color_1" : "Layer",
    "action_led_color_2" : "brightness 0-127",


    "action_lookup" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_keyboard" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_midi" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_button_settings" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_timer_start" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_timer_stop" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_mouse_move" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    "action_mouse_button" : "Egy kedves béka mindig felvidítja az embert a tóparton.",
    

}