<script>
  import { onMount } from 'svelte';

  import ColorPicker from '../ColorPicker.svelte';

  import DropDownInput from '../DropDownInput.svelte';

  export let data;

  let layers = [];
  let startColor;
  let alpha = 1;
  let parameters = [
    {value: 'A0', info: 'This LED.'}, 
    {value: 'A1', info: 'Reversed LED.'}, 
  ];

  data.parameters[1] = layers;  

  // init string '' generated by elementsettings.svelte from NaN to 0;

  function colorCallback(rgba) {
    //console.log('colorCallback()',rgba.detail)
    data.parameters[2] = rgba.detail.r
    data.parameters[3] = rgba.detail.g 
    data.parameters[4] = rgba.detail.b
    data.parameters[5] = rgba.detail.a;
    //console.log(data.parameters[3]);
  }

  function rgb2hex(rgb){
    rgb = rgb.match(/^rgba?[\s+]?\([\s+]?(\d+)[\s+]?,[\s+]?(\d+)[\s+]?,[\s+]?(\d+)[\s+]?/i);
    return (rgb && rgb.length === 4) ? "#" +
      ("0" + parseInt(rgb[1],10).toString(16)).slice(-2) +
      ("0" + parseInt(rgb[2],10).toString(16)).slice(-2) +
      ("0" + parseInt(rgb[3],10).toString(16)).slice(-2) : '';
  }

  // number, layer, r, g, b, preview
 

  onMount(()=>{
    // this may be needed to put in a $: for reactivity but seems to work anyway
    console.log(data.parameters);
    if(data.parameters[2] === ''){
      data.parameters[2] = 255;
      data.parameters[3] = 0;
      data.parameters[4] = 0;
      data.parameters[5] = 1;
    } 
    const color = `rgb(${data.parameters[2]}, ${data.parameters[3]}, ${data.parameters[4]})`
    startColor = rgb2hex(color).toUpperCase();
    
    alpha = data.parameters[5];
  })

</script>

<div class="flex flex-col">
  <div class="flex w-full items-center">
    <div class="w-3/12 flex">
      <DropDownInput optionList={parameters} bind:dropDownValue={data.parameters[0]}/>
    </div>
    <div class="flex w-3/12 justify-around">
      <div class="mx-1 flex ">
        <div class="text-white mr-1">A</div>
        <input bind:group={layers} value={'A'} type="checkbox" class="h-6 w-6">
      </div>
      <div class="mx-1 flex">
        <div class="text-white pr-1">B</div>
        <input bind:group={layers} value={'B'} type="checkbox" class="h-6 w-6">
      </div>
    </div>
    <div class="flex w-6/12">
      <input type="number" bind:value={data.parameters[2]} min=0 max=255 class="mx-1 w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      <input type="number" bind:value={data.parameters[3]} min=0 max=255 class="mx-1 w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      <input type="number" bind:value={data.parameters[4]} min=0 max=255 class="mx-1 mr-2 w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
    </div>
  </div>

  <div class="mt-2">
    {#if startColor && alpha}
      <ColorPicker {startColor} {alpha} on:colorChange={colorCallback}/>
    {/if}
  </div>
</div>