<script>
  import { onMount } from 'svelte';

  import { GRID_PROTOCOL } from '../../serialport/GridProtocol.js';

  import { serialComm } from '../../serialport/serialport.store';

  import { configStore } from '../../stores/config.store';

  import ColorPicker from '../ColorPicker.svelte';

  import DropDownInput from '../DropDownInput.svelte';

  export let data;
  export let index;
  export let selectedElementSettings;
  export let moduleInfo;
  export let eventInfo;

  function sendData(){

    console.log('change of data',data.parameters);

    data.valid = setLedColorValidator(data.parameters);

    data.parameters[1] = layers;
    
    let parameterArray = [];
    for (let i = 0; i < data.parameters[1].length; i++) {
      let param_0;
      if(data.parameters[0] !== 'A0' || data.parameters[0] !== 'A1'){ param_0 = Number(data.parameters[0]) }
      const parameters = [
        { 'NUM': param_0 },
        { 'LAY': data.parameters[1][i] },
        { 'RED': Math.floor(data.parameters[2] * data.parameters[5]) },
        { 'GRE': Math.floor(data.parameters[3] * data.parameters[5]) },
        { 'BLU': Math.floor(data.parameters[4] * data.parameters[5]) }
      ];
      parameterArray.push(parameters);
    }

    //console.log('set led color on module...', moduleInfo)

    parameterArray.forEach(parameters => {
      configStore.save(index, moduleInfo, eventInfo, selectedElementSettings, GRID_PROTOCOL.configure("LEDCOLOR", parameters));
    });
    
  }

  let layers = data.parameters[1];

  let startColor;
  let alpha = 1;
  let parameters = [
    {value: 'A0', info: 'This LED.'}, 
    {value: 'A1', info: 'Reversed LED.'}, 
  ];

  data.parameters[1] = layers;  

  // init string '' generated by elementsettings.svelte from NaN to 0;

  
  function colorCallback(rgba) {

    data.parameters[2] = Math.floor(rgba.detail.r)
    data.parameters[3] = Math.floor(rgba.detail.g)
    data.parameters[4] = Math.floor(rgba.detail.b)
    data.parameters[5] = rgba.detail.a;

    sendData();

  }

  function setLedColorValidator(parameters){
    const num = data.parameters[0];
    const lay = data.parameters[1];
    const red = data.parameters[2];
    const gre = data.parameters[3];
    const blu = data.parameters[4];
    let valid = true;
    if(!(num == 'A0' || num == 'A1' || 0 < num && num < 16 )) valid = false;
    if(!(lay.length > 0)) valid = false;
    if(!(0 <= red && red <= 255)) valid = false;
    if(!(0 <= gre && gre <= 255)) valid = false;
    if(!(0 <= blu && blu <= 255)) valid = false;
    return valid;
  }


  onMount(()=>{
    // this may be needed to put in a $: for reactivity but seems to work anyway
 
    if(data.parameters[2] === ''){
      data.parameters[1] = ['','']
      data.parameters[2] = 255;
      data.parameters[3] = 0;
      data.parameters[4] = 0;
      data.parameters[5] = 1;
    } 

    console.log('onMount data.parameters: ',eventInfo);

    startColor = `rgb(${data.parameters[2]}, ${data.parameters[3]}, ${data.parameters[4]})`

    alpha = data.parameters[5];

    data.parameters[0] = selectedElementSettings.controlNumber[0];

  })

</script>

<div class="flex flex-col w-full">
  <div class="flex w-full text-white">
    <div class="flex w-5/12 flex-col xl:flex-row">
      <div class="w-full xl:w-5/12">
        <div class="text-gray-700 text-xs">Element</div>
        <DropDownInput optionList={parameters} bind:dropDownValue={data.parameters[0]}/>
      </div>
      <div class="w-full xl:w-7/12">
        <div class="text-gray-700 text-xs">Layer</div>
        <div class="flex justify-around my-1">
          <div class="mx-1 flex ">
            <div class="text-white mr-1">A</div>
            <input bind:group={layers} value={1} on:change={sendData} type="checkbox" class="h-6 w-6">
          </div>
          <div class="mx-1 flex ">
            <div class="text-white pr-1">B</div>
            <input bind:group={layers} value={2} on:change={sendData} type="checkbox" class="h-6 w-6">
          </div>
        </div>
      </div>
    </div>
    <div class="flex w-7/12 flex-col xl:flex-row">
      <div class="px-1">
        <div class="text-gray-700 text-xs">Red</div>
        <input type="number" bind:value={data.parameters[2]} on:change={sendData} min=0 max=255 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      <div class="px-1">
        <div class="text-gray-700 text-xs">Green</div>
        <input type="number" bind:value={data.parameters[3]} on:change={sendData} min=0 max=255 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      <div class="px-1">
        <div class="text-gray-700 text-xs">Blue</div>
        <input type="number" bind:value={data.parameters[4]} on:change={sendData} min=0 max=255 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      <div class="px-1 xl:pr-2">
        <div class="text-gray-700 text-xs">Alpha</div>
        <input type="number" bind:value={data.parameters[5]} on:change={sendData} min=0 max=1 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
    </div>
  </div>

  <div class="mt-2 pr-1 xl:pr-2 w-full">
    {#if startColor}
      <ColorPicker {startColor} {alpha} on:colorChange={colorCallback}/>
    {/if}
  </div>

</div>