<script>
  import { onMount } from 'svelte';

  import { GRID_PROTOCOL } from '../../serialport/GridProtocol.js';

  import { serialComm } from '../../serialport/serialport.store';

  import { configStore } from '../../stores/config.store';

  import ColorPicker from '../ColorPicker.svelte';

  import DropDownInput from '../DropDownInput.svelte';

  export let data;
  export let orderNumber;
  export let selectedElementSettings;
  export let moduleInfo;
  export let eventInfo;

  function sendData(){

    //data.valid = setLedColorValidator(data.parameters);

    data.parameters[1] = layers;
    
    let parameterArray = [];
    for (let i = 0; i < data.parameters[1].length; i++) {
      let param_0;
      let param_2;
      if(data.parameters[0] != 'A0' && data.parameters[0] != 'A1'){ param_0 = Number(data.parameters[0]) } else { param_0 = data.parameters[0]}
      if(data.parameters[2] != 'A3' && data.parameters[2] != 'A7'){ param_2 = Number(data.parameters[2]) } else { param_2 = data.parameters[2]}
      const parameters = [
        { 'NUM': param_0 },
        { 'LAY': data.parameters[1][i] },
        { 'PHA': param_2 },
      ];
      parameterArray.push(parameters);
    }

    let serialized = [];
    parameterArray.forEach((parameters,i) => {
      serialized.push(...GRID_PROTOCOL.configure("LEDPHASE", parameters));
    });

    configStore.save(orderNumber, moduleInfo, eventInfo, selectedElementSettings, serialized);
  }

  let layers = data.parameters[1];

  let startColor;
  let alpha = 1;
  let parameters = [
    [
      {value: 'A0', info: 'This LED.'}, 
      {value: 'A1', info: 'Reversed LED.'}, 
    ],
    [
      {value: 'A3', info: 'AV8'}, 
      {value: 'A7', info: 'DV8'}, 
    ]
  ];

  // init string '' generated by elementsettings.svelte from NaN to 0;

  onMount(()=>{

  })

</script>

<div class="flex flex-col w-full">
  <div class="flex w-full text-white">
    <div class=" w-1/3">
      <div class="text-gray-700 text-xs">Element</div>
      <DropDownInput optionList={parameters[0]} on:change={sendData} bind:dropDownValue={data.parameters[0]}/>
    </div>
    <div class="w-1/3">
      <div class="text-gray-700 text-xs">Layer</div>
      <div class="flex justify-around my-1">
        <div class="mx-1 flex ">
          <div class="text-white mr-1">A</div>
          <input bind:group={layers} value={1} on:change={sendData} type="checkbox" class="h-6 w-6">
        </div>
        <div class="mx-1 flex ">
          <div class="text-white pr-1">B</div>
          <input bind:group={layers} value={2} on:change={sendData} type="checkbox" class="h-6 w-6">
        </div>
      </div>
    </div>

    <div class="flex w-1/3">
      <div class="px-1">
        <div class="text-gray-700 text-xs">Intensity</div>
        <DropDownInput optionList={parameters[1]} on:change={sendData} bind:dropDownValue={data.parameters[2]}/>
      </div>
    </div>
  </div>

</div>