<script>
  import { onMount, createEventDispatcher, afterUpdate } from 'svelte';

  const dispatch = createEventDispatcher();

  import { GRID_PROTOCOL } from '../../../core/classes/GridProtocol.js';

  import { actionListChange } from '../action-list-change.store.js';

  import { configStore } from '../../../stores/config.store';

  import ColorPicker from '../../ui/components/ColorPicker.svelte';

  import DropDownInput from '../../ui/components/DropDownInput.svelte';

  export let action;
  export let index;

  let orderChangeTrigger = null;

  onMount(()=>{

    startColor = `rgb(${action.parameters.RED}, ${action.parameters.GRE}, ${action.parameters.BLU})`

    let c = 0;
    actionListChange.subscribe((change)=>{
      c++;
      console.log( action.name, 'order change subscription', index);
      if(change !== null && c == 1){
        orderChangeTrigger = true;
      }
      c = 0;
    });
  })

  afterUpdate(() => {
    if(orderChangeTrigger){
      sendData();
    }
  })

  function sendData(){
    
    let param_0;
    if(action.parameters.NUM != 'A0' && action.parameters.NUM != 'A1'){ 
      param_0 = Number(action.parameters.NUM) 
    } else { 
      param_0 = action.parameters.NUM
    }

    const parameters = [
      { 'NUM': param_0 },
      { 'LAY': action.parameters.LAY },
      { 'RED': Math.floor(action.parameters.RED) },
      { 'GRE': Math.floor(action.parameters.GRE) },
      { 'BLU': Math.floor(action.parameters.BLU) },
      //{ 'BLU': Math.floor(action.parameters.BLU * action.parameters.ALPHA) }
    ];

    let valid = setLedColorValidator(action.parameters);

    console.log('set led color...',valid, parameters);
     
    if(valid){    
      dispatch('send',{
        action: {
          value: action.value, 
          parameters: parameters
        }, 
        index: index 
      });
    }
  }

  let layers = action.parameters[1] || []; 

  let startColor;
  let alpha = 1;
  let parameters = [
    [
      {value: 'A0', info: 'This LED.'}, 
      {value: 'A1', info: 'Reversed LED.'}, 
    ],
    [
      {value: 'A', info: 'A Layer'}, 
      {value: 'B', info: 'B Layer'}, 
    ]
  ];


  // init string '' generated by elementsettings.svelte from NaN to 0;

  
  function colorCallback(rgba) {

    action.parameters.RED = Math.floor(rgba.detail.r)
    action.parameters.GRE = Math.floor(rgba.detail.g)
    action.parameters.BLU = Math.floor(rgba.detail.b)
    action.parameters.ALPHA = rgba.detail.a;

    sendData();

  }

  function setLedColorValidator(parameters){
    const num = parameters.NUM;
    const lay = parameters.LAY;
    const red = parameters.RED;
    const gre = parameters.GRE;
    const blu = parameters.BLU;
    let valid = true;
    if(!(num == 'A0' || num == 'A1' || 0 < num && num < 16 )) valid = false;
    if(!(lay.length > 0 || lay[0] !== '')) valid = false;
    if(!(0 <= red && red <= 255)) valid = false;
    if(!(0 <= gre && gre <= 255)) valid = false;
    if(!(0 <= blu && blu <= 255)) valid = false;
    return valid;
  }


</script>

<div class="flex flex-col w-full pr-1 xl:pr-0">
  <div class="flex w-full text-white">
    <div class="flex w-5/12 flex-col pr-1 xl:pr-0 xl:flex-row">
      <div class="w-full xl:pr-1">
        <div class="text-gray-700 text-xs">Element</div>
        <DropDownInput on:change={()=>{sendData()}} optionList={parameters[0]} bind:dropDownValue={action.parameters.NUM}/>
      </div>
      <div class="w-full xl:px-1">
        <div class="text-gray-700 text-xs">Layer</div>
        <DropDownInput on:change={()=>{sendData()}} optionList={parameters[1]} bind:dropDownValue={action.parameters.LAY}/>
      </div>
    </div>
    <div class="flex w-full flex-col xl:flex-row">
      <div class="px-1 w-full">
        <div class="text-gray-700 text-xs">Red</div>
        <input type="number" bind:value={action.parameters.RED} on:change={sendData} min=0 max=255 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      <div class="px-1 w-full">
        <div class="text-gray-700 text-xs">Green</div>
        <input type="number" bind:value={action.parameters.GRE} on:change={sendData} min=0 max=255 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      <div class="px-1 w-full xl:pr-2">
        <div class="text-gray-700 text-xs">Blue</div>
        <input type="number" bind:value={action.parameters.BLU} on:change={sendData} min=0 max=255 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      <!--
      <div class="px-1 w-full xl:pr-2">
        <div class="text-gray-700 text-xs">Alpha</div>
        <input type="number" bind:value={action.parameters.ALPHA} on:change={sendData} min=0 max=1 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      -->
    </div>
  </div>

  <div class="mt-2 pr-1 xl:pr-2 w-full">
    {#if startColor}
      <ColorPicker {startColor} showAlpha={false} {alpha} on:colorChange={colorCallback}/>
    {/if}
  </div>

</div>

<style>

input::-webkit-inner-spin-button {
    display: none;
    -webkit-appearance: none;
    margin: 0; /* <-- Apparently some margin are still there even though it's hidden */
}

</style>