<script>
  import { onMount, createEventDispatcher, afterUpdate } from 'svelte';

  const dispatch = createEventDispatcher();

  import { GRID_PROTOCOL } from '../../../core/protocol/GridProtocol.js';

  import { actionListChange } from '../action-list-change.store.js';

  import { configStore } from '../../../stores/config.store';

  import ColorPicker from '../../ui/components/ColorPicker.svelte';

  import DropDownInput from '../../ui/components/DropDownInput.svelte';

  export let data;
  export let orderNumber;
  export let selectedElementSettings;
  export let moduleInfo;
  export let eventInfo;

  let orderChangeTrigger = null;

  onMount(()=>{

    if(data.parameters[2] === ''){
      data.parameters[1] = ['','']
      data.parameters[2] = 255;
      data.parameters[3] = 0;
      data.parameters[4] = 0;
      data.parameters[5] = 1;
    } 

    startColor = `rgb(${data.parameters[2]}, ${data.parameters[3]}, ${data.parameters[4]})`

    alpha = data.parameters[5];

    data.parameters[0] = parameters[0].value;

    let c = 0;
    actionListChange.subscribe((change)=>{
      c++;
      console.log( data.name, 'order change subscription', orderNumber);
      if(change !== null && c == 1){
        orderChangeTrigger = true;
      }
      c = 0;
    });
  })

  afterUpdate(() => {
    if(orderChangeTrigger){
      sendData();
    }
  })

  function sendData(){

    data.parameters[1] = layers;
    
    let parameterArray = [];
    for (let i = 0; i < data.parameters[1].length; i++) {
      let param_0;
      if(data.parameters[0] != 'A0' && data.parameters[0] != 'A1'){ param_0 = Number(data.parameters[0]) } else { param_0 = data.parameters[0]}
      const parameters = [
        { 'NUM': param_0 },
        { 'LAY': data.parameters[1][i] },
        { 'RED': Math.floor(data.parameters[2] * data.parameters[5]) },
        { 'GRE': Math.floor(data.parameters[3] * data.parameters[5]) },
        { 'BLU': Math.floor(data.parameters[4] * data.parameters[5]) }
      ];
      let valid = setLedColorValidator(data.parameters);
      parameterArray.push({parameters: parameters, valid: valid});
    }

    let serialized = [];
    parameterArray.forEach(p => {
      if(p.valid){
        serialized.push(...GRID_PROTOCOL.configure("LEDCOLOR", p.parameters));
      }
    });

    if(serialized.length !== 0){
      configStore.save(orderNumber, moduleInfo, eventInfo, selectedElementSettings, serialized);
    }

    dispatch('send',{});
  }

  let layers = data.parameters[1];

  let startColor;
  let alpha = 1;
  let parameters = [
    {value: 'A0', info: 'This LED.'}, 
    {value: 'A1', info: 'Reversed LED.'}, 
  ];

  data.parameters[1] = layers;  

  // init string '' generated by elementsettings.svelte from NaN to 0;

  
  function colorCallback(rgba) {

    data.parameters[2] = Math.floor(rgba.detail.r)
    data.parameters[3] = Math.floor(rgba.detail.g)
    data.parameters[4] = Math.floor(rgba.detail.b)
    data.parameters[5] = rgba.detail.a;

    sendData();

  }

  function setLedColorValidator(parameters){
    const num = parameters[0];
    const lay = parameters[1];
    const red = parameters[2];
    const gre = parameters[3];
    const blu = parameters[4];
    let valid = true;
    if(!(num == 'A0' || num == 'A1' || 0 < num && num < 16 )) valid = false;
    if(!(lay.length > 0 || lay[0] !== '')) valid = false;
    if(!(0 <= red && red <= 255)) valid = false;
    if(!(0 <= gre && gre <= 255)) valid = false;
    if(!(0 <= blu && blu <= 255)) valid = false;
    return valid;
  }


</script>

<div class="flex flex-col w-full">
  <div class="flex w-full text-white">
    <div class="flex w-5/12 flex-col xl:flex-row">
      <div class="w-full xl:w-5/12">
        <div class="text-gray-700 text-xs">Element</div>
        <DropDownInput optionList={parameters} bind:dropDownValue={data.parameters[0]}/>
      </div>
      <div class="w-full xl:w-7/12">
        <div class="text-gray-700 text-xs">Layer</div>
        <div class="flex justify-around my-1">
          <div class="mx-1 flex ">
            <div class="text-white mr-1">A</div>
            <input bind:group={layers} value={1} on:change={sendData} type="checkbox" class="h-6 w-6">
          </div>
          <div class="mx-1 flex ">
            <div class="text-white pr-1">B</div>
            <input bind:group={layers} value={2} on:change={sendData} type="checkbox" class="h-6 w-6">
          </div>
        </div>
      </div>
    </div>
    <div class="flex w-7/12 flex-col xl:flex-row">
      <div class="px-1">
        <div class="text-gray-700 text-xs">Red</div>
        <input type="number" bind:value={data.parameters[2]} on:change={sendData} min=0 max=255 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      <div class="px-1">
        <div class="text-gray-700 text-xs">Green</div>
        <input type="number" bind:value={data.parameters[3]} on:change={sendData} min=0 max=255 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      <div class="px-1">
        <div class="text-gray-700 text-xs">Blue</div>
        <input type="number" bind:value={data.parameters[4]} on:change={sendData} min=0 max=255 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
      <div class="px-1 xl:pr-2">
        <div class="text-gray-700 text-xs">Alpha</div>
        <input type="number" bind:value={data.parameters[5]} on:change={sendData} min=0 max=1 class="w-full secondary text-white p-1 pl-2 rounded-none focus:outline-none">
      </div>
    </div>
  </div>

  <div class="mt-2 pr-1 xl:pr-2 w-full">
    {#if startColor}
      <ColorPicker {startColor} {alpha} on:colorChange={colorCallback}/>
    {/if}
  </div>

</div>