name: 💀 Alpha build

on:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+-alpha*"

jobs:
  matrix-build:
    uses: ./.github/workflows/build-matrix.yml
    with:
      exportScript: export
      versionOverride: ${{ github.ref_name }}
    secrets: inherit

  publish-alpha:
    runs-on: ubuntu-latest
    needs: matrix-build
    steps:
      - name: Download all nightly artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*-artifact" # This will match ubuntu-latest-artifact, windows-latest-artifact, and macos-latest-artifact
          path: build/ # Path to save the downloaded artifacts
          merge-multiple: true
      - name: Rename files from *-artifact to *
        run: rename 's/-artifact$/-alpha/' ./build/*-artifact*
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/*.*
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-unit-test:
    uses: ./.github/workflows/linux-unit-test.yml
    secrets: inherit
