name: Build matrix

on:
  workflow_call:
    inputs:
      exportScript:
        description: "The npm script to run for export"
        required: true
        type: string
      versionOverride:
        description: "Override package version string"
        required: false
        type: string

jobs:
  set-branch-name:
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.set-branch-name-shell.outputs.branch_name }}
    steps:
      - name: Set VITE_BRANCH_NAME
        id: set-branch-name-shell
        run: |
          if [ "${{ github.ref_type }}" == "tag" ]; then
            echo "branch_name=stable" >> $GITHUB_OUTPUT
          else
            echo "branch_name=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          fi
        shell: bash

  matrix-build:
    needs: set-branch-name
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ""
          submodules: true

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "24"
          cache: "npm"

      - name: Install python setup-tools dependency
        run: pip install setuptools
        env:
          PIP_BREAK_SYSTEM_PACKAGES: 1

      - name: Install dependencies
        run: npm ci

      - name: Download LuaLS binaries
        run: node build-scripts/download-luals.js

      - name: Update package.json
        if: ${{ inputs.versionOverride != '' }}
        run: npm version ${{ inputs.versionOverride }} --no-git-tag-version

      - name: Build package
        run: npm run ${{ inputs.exportScript }}
        env:
          # gh repo token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # windows Code signing
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

          # Apple ID
          APPLE_ID: ${{secrets.APPLE_ID}}
          APPLE_TEAM_ID: ${{secrets.APPLE_TEAM_ID}}
          APPLE_APP_SPECIFIC_PASSWORD: ${{secrets.APPLE_APP_SPECIFIC_PASSWORD}}

          # macOS Code signing
          CSC_LINK: ${{ secrets.MAC_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CSC_KEY_PASSWORD }}

          VITE_BRANCH_NAME: ${{needs.set-branch-name.outputs.branch_name}}

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-artifact
          path: build/*.*

      - name: Find arm64.dmg file in build
        if: runner.os == 'macOS'
        id: find_dmg
        run: |
          FILE=$(find build -type f -name "*arm64.dmg" | head -n 1)
          echo "file=$FILE" >> $GITHUB_OUTPUT
          echo "name=$(basename "$FILE")" >> $GITHUB_OUTPUT

      - name: Upload arm64.dmg with dynamic name
        if: runner.os == 'macOS' && steps.find_dmg.outputs.file != ''
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.find_dmg.outputs.name }}
          path: ${{ steps.find_dmg.outputs.file }}
