name: Deploy to Firebase Hosting on main branch push
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i && npm run web-build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GRID_EDITOR_WEB }}"
          projectId: grid-editor-web
      - run: echo ${{steps.firebase_deploy.outputs.urls}}
