name: Formatting validator

on: push

jobs:
  formatting-validator:
    name: Prettier validation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ""
          submodules: true

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"

      - name: Install dependencies
        run: |
          npm i prettier --global
          npm i prettier-plugin-svelte --global
          prettier --write .
          git status
          touch format_error.txt
          echo 'Changed Files:'
          git diff --name-only
          git diff --name-only >> format_error.txt
          if [ -s format_error.txt ]; then
            echo "ERROR IN FORMATTING, PLEASE RUN PRETTIER ON THE CODEBASE BEFORE COMMITTING"
            exit 1
          fi

      - uses: tsickert/discord-webhook@v4.0.0
        if: ${{ failure() }}
        with:
          webhook-url: ${{ secrets.DISCORD_DEV_WEBHOOK }}
          content: "Format error in the following files!"
          filename: "format_error.txt"
