name: Playwright Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"

# only one workflow is running at the same time for each branch
# concurrency:
#   group: ${{ github.ref_name }}
#   # optional
#   cancel-in-progress: true

jobs:
  test:
    name: Web build test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.1"
      - name: Install libudev-dev
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - run: npm ci
      - name: Install Playwright Chromium Browser
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        env:
          CI: true
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  publish_report:
    name: Publish HTML Report
    # using always() is not ideal here, because it would also run if the workflow was cancelled
    if: "success() || needs.test.result == 'failure'"
    needs: [test]
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      # Unique URL path for each workflow run attempt
      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
    steps:
      - name: Download zipped HTML report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ${{ env.HTML_REPORT_URL_PATH }}
      - name: Deploy to Firebase Hosting (Reports Site)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_GRID_EDITOR_WEB }}"
          projectId: grid-editor-web
          target: playwright-preview
          expires: 7d

      - name: Output Preview URL
        run: |
          echo "::notice title=📋 Playwright Report Preview::${{ steps.firebase_deploy.outputs.details_url }}"

# # HEADED MODE
#  name: Playwright Tests

# on:
#   push:
#     branches:
#       - "**"
#     tags-ignore:
#       - "*"

# jobs:
#   web-build-test:
#     runs-on: ubuntu-latest
#     timeout-minutes: 10

#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup NodeJs
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18.16.1"

#       - name: Install dependencies and build
#         run: npm install && npm run web-build

#       - name: Install Playwright Chromium Browser
#         run: npx playwright install --with-deps chromium

#       - name: Run Playwright tests in headed mode
#         run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npx playwright test --headed
#         env:
#           CI: true

#       - name: Upload Playwright report
#         uses: actions/upload-artifact@v3
#         if: always()
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 30
