name: Playwright Tests

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "*"

# only one workflow is running at the same time for each branch
# concurrency:
#   group: ${{ github.ref_name }}
#   # optional
#   cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.1"
      - run: npm ci
      - name: Install Playwright Chromium Browser
        run: npx playwright install --with-deps chromium
      - name: Run Playwright tests
        env:
          CI: true
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  publish_report:
    name: Publish HTML Report
    # using always() is not ideal here, because it would also run if the workflow was cancelled
    if: "success() || needs.test.result == 'failure'"
    needs: [test]
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      # Unique URL path for each workflow run attempt
      HTML_REPORT_URL_PATH: reports/${{ github.ref_name }}/${{ github.run_id }}/${{ github.run_attempt }}
    steps:
      - name: Checkout GitHub Pages Branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
      - name: Set Git User
        # see: https://github.com/actions/checkout/issues/13#issuecomment-724415212
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Download zipped HTML report
        uses: actions/download-artifact@v4
        with:
          name: playwright-report
          path: ${{ env.HTML_REPORT_URL_PATH }}
      - name: Push HTML Report
        timeout-minutes: 3
        # commit report, then try push-rebase-loop until it's able to merge the HTML report to the gh-pages branch
        # this is necessary when this job is running at least twice at the same time (e.g. through two pushes at the same time)
        run: |
          git add .
          git commit -m "workflow: add HTML report for run-id ${{ github.run_id }} (attempt:  ${{ github.run_attempt }})"

          while true; do
            git pull --rebase
            if [ $? -ne 0 ]; then
              echo "Failed to rebase. Please review manually."
              exit 1
            fi

            git push
            if [ $? -eq 0 ]; then
              echo "Successfully pushed HTML report to repo."
              exit 0
            fi
          done
      - name: Output Report URL as Worfklow Annotation
        run: |
          FULL_HTML_REPORT_URL=https://ysfaran.github.io/playwright-gh-actions-gh-pages/$HTML_REPORT_URL_PATH

          echo "::notice title=📋 Published Playwright Test Report::$FULL_HTML_REPORT_URL"

# # HEADED MODE
#  name: Playwright Tests

# on:
#   push:
#     branches:
#       - "**"
#     tags-ignore:
#       - "*"

# jobs:
#   web-build-test:
#     runs-on: ubuntu-latest
#     timeout-minutes: 10

#     steps:
#       - uses: actions/checkout@v4
#       - name: Setup NodeJs
#         uses: actions/setup-node@v3
#         with:
#           node-version: "18.16.1"

#       - name: Install dependencies and build
#         run: npm install && npm run web-build

#       - name: Install Playwright Chromium Browser
#         run: npx playwright install --with-deps chromium

#       - name: Run Playwright tests in headed mode
#         run: xvfb-run --auto-servernum --server-args="-screen 0 1920x1080x24" npx playwright test --headed
#         env:
#           CI: true

#       - name: Upload Playwright report
#         uses: actions/upload-artifact@v3
#         if: always()
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 30
