name: Build Stable Grid Editor

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  win-build:
    name: Windows Build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ""
          submodules: true

      - name: Update configuration.json NODE_ENV
        uses: jossef/action-set-json-field@v2.1
        with:
          file: configuration.json
          field: NODE_ENV
          value: production

      - name: Set env
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: See env
        run: echo "${{ env.RELEASE_VERSION }}"

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run export
        env:
          # gh repo token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # windows Code signing
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}

      - name: See directory
        run: ls build/*.*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          files: build/*.*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  macos-build:
    name: MacOS Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ""
          submodules: true

      - name: Update configuration.json NODE_ENV
        uses: jossef/action-set-json-field@v2.1
        with:
          file: configuration.json
          field: NODE_ENV
          value: production

      - name: Set env
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: See env
        run: echo "${{ env.RELEASE_VERSION }}"

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run export
        env:
          # gh repo token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # macOS Code signing certificates
          CSC_LINK: ${{ secrets.MAC_CSC_LINK }}
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CSC_KEY_PASSWORD }}

          # macOS notarization API key
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}

      - name: See directory
        run: ls build/*.*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          files: build/*.*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ""
          submodules: true

      - name: Update configuration.json NODE_ENV
        uses: jossef/action-set-json-field@v2.1
        with:
          file: configuration.json
          field: NODE_ENV
          value: production

      - name: Set env
        shell: bash
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: See env
        run: echo "${{ env.RELEASE_VERSION }}"

      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "16.13.2"

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run export
        env:
          # gh repo token
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: See directory
        run: ls build/*.*

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.RELEASE_VERSION }}
          name: Release ${{ env.RELEASE_VERSION }}
          files: build/*.*
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
