name: 🚀 Release build

on:
  workflow_dispatch:
  push:
    tags:
      - "v[12].[0-9]+.[0-9]+"

jobs:
  matrix-build:
    uses: ./.github/workflows/build-matrix.yml
    with:
      exportScript: export
    secrets: inherit

  publish-release:
    runs-on: ubuntu-latest
    needs: matrix-build
    steps:
      - name: Download all nightly artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: "*-artifact" # This will match ubuntu-latest-artifact, windows-latest-artifact, and macos-latest-artifact
          path: build/ # Path to save the downloaded artifacts
          merge-multiple: true
      - name: Remove *-artifact from file name
        run: |
          for file in $(find ./build -type f -name '*-artifact*'); do
            new_file=$(echo "$file" | sed 's/-artifact//g')
            mv "$file" "$new_file"
          done

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build/*.*
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
